### PR TITLE
ChangeLog in Markdown format

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by ianfixes** [comment]
Which commit should we pick for the latest "release"?  I can add those tags now so that you can refer to them at the bottom of the document (see the bottom of the [BasiliskII changelog](https://github.com/emaculation/BasiliskII/blame/master/CHANGELOG.md#L522-L523)):

```markdown
[Unreleased]: https://github.com/emaculation/BasiliskII/compare/v1.0...HEAD
[v1.0.0]: https://github.com/emaculation/BasiliskII/compare/v0.0.0...v1.0.0
```

**Comment by retokromer** [comment]
Not sure I understand. Both links give me: "There isn’t anything to compare."

Possibly `v3.2.0...HEAD` and `v0.0.0...v3.2.0`.

**Comment by ianfixes** [comment]
These links work by referring to tags in git (which go into the URL format shown in those links).  But to make it work, we have to actually choose some commits to tag.  `v0.0.0` is easy -- we point it to the initial commit. But which commit should we use for `v3.2.0`?

**Comment by retokromer** [comment]
>But which commit should we use for `v3.2.0`?

The last one before changes have been made here?

**Comment by retokromer** [comment]
Closing: seems not to be of interest.

**Comment by ianfixes** [comment]
My fault on this, I didn't realize that the failing CI tests here were due to Appveyor running (as it should not have been), and thought that this was still a work in progress.  A bit of that got lost in the shuffle when re-combining the Basilisk and SheepShaver repos.

**Comment by ianfixes** [comment]
I fixed the Appveyor settings, so it should no longer run when there isn't an Appveyor config file.  If you reopen this, I will merge.

**Pull request closed without merging**
