### PR TITLE
Add Windows CI support (help wanted: Cygwin)

### PR DESCRIPTION
**Pull request by ianfixes**
This can't go forward unless/until someone knows how to invoke `aclocal` in a Cygwin environment

### CODE REVIEW

**Comment by retokromer** [comment]
Sorry, I cannot help on this one, because building on Cygwin has ever been a failure-prone task to me… I guess, you should consider cross-compiling from Linux either on a virtual machine, via dual-boot or from another computer.

**Comment by davewongillies** [comment]
@ianfixes I've gotten it finding the commands now in #14 , just blocked on the `configure` not being able to find libraries.

**Comment by ianfixes** [comment]
It looks like the error is related to not being able to find a terminal library: https://stackoverflow.com/q/12290783/2063546

But that's confusing, since we manually install `libncurses-devel` at the beginning of the build process.

**Comment by davewongillies** [comment]
@ianfixes here's a [working build](https://ci.appveyor.com/project/davewongillies/cxmon/builds/25881924). It looks like the extra `C:\cygwin\bin` in the `$PATH` was causing the issues: https://github.com/davewongillies/cxmon/blob/appveyor/appveyor.yml#L8

**Comment by ianfixes** [comment]
😮 THANK YOU!

I could use your help on https://github.com/emaculation/macemu/pull/106 too...

**Pull request merged**
